name: Q1 Workflow

on:
  push:
    paths:
      - README.md

jobs:
  copy-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy README.md to Q1_archive_README.md
        run: cp README.md Q1_archive_README.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Q1_archive_README.md
          git commit -m "Add Q1_archive_README.md" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
