name: Q3 Workflow

on:
  push:
    paths:
      - Q3.java

jobs:
  archive-java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Q3_archive_java.txt
        run: |
          echo "Nom: Votre Nom" > Q3_archive_java.txt
          echo "Prénom: Votre Prénom" >> Q3_archive_java.txt
          echo "" >> Q3_archive_java.txt
          echo "Contenu du fichier Q3.java :" >> Q3_archive_java.txt
          echo "" >> Q3_archive_java.txt
          cat Q3.java >> Q3_archive_java.txt

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Q3_archive_java.txt
          git commit -m "Add Q3_archive_java.txt" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

