name: Q5 Workflow

on:
  push:
    paths:
      - Q5.java

jobs:
  archive-java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Q5_archive_date.txt
        run: |
          filename="Q5_archive_$(date '+%d-%m-%Y').txt"
          echo "Nom: Marouard" > $filename
          echo "Prénom: Louis" >> $filename
          cat Q5.java >> $filename

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          commit_message: "Add Q5_archive_date.txt"
