name: Q6 Workflow

on:
  push:
    paths:
      - Q6.java

jobs:
  archive-java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get current date and time
        id: date
        run: |
          current_date=$(date '+%d-%m-%Y-%H%M%S')
          echo "current_date=$current_date" >> $GITHUB_ENV

      - name: Create Q6_archive_date.txt
        run: |
          archive_file="Q6_archive_${{ env.current_date }}.txt"
          echo "Nom: Votre Nom" > $archive_file
          echo "Prénom: Votre Prénom" >> $archive_file
          echo "" >> $archive_file
          echo "Contenu du fichier Q6.java :" >> $archive_file
          echo "" >> $archive_file
          cat Q6.java >> $archive_file
          echo "" >> $archive_file
          echo "Taille du fichier Q6.java :" >> $archive_file
          wc -l Q6.java >> $archive_file
          wc -c Q6.java >> $archive_file

      - name: Compare with previous archive and create Q6_différences.txt
        run: |
          # Trouver le dernier fichier d'archive créé
          last_archive=$(ls Q6_archive_*.txt | sort -r | head -n 1)

          # Vérifier si un fichier précédent existe
          if [ -f "$last_archive" ]; then
            # Si le fichier existe, comparer avec le fichier actuel
            diff $last_archive Q6_archive_${{ env.current_date }}.txt > Q6_différences.txt
          else
            # Si aucun fichier précédent n'existe, indiquer qu'il n'y a pas de comparaison possible
            echo "Aucun fichier précédent pour comparer." > Q6_différences.txt
          fi

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Q6_archive_*.txt Q6_différences.txt
          git commit -m "Add Q6 archive and differences for ${{ env.current_date }}" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
